name: CI/CD Docker Build

# Phần này quan trọng nhất: Định nghĩa KHI NÀO chạy
on:
  push:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Lấy code về
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thử Build Docker
      - name: Test Build Docker Image
        run: docker build . --file Dockerfile --tag my-web-app:latest

      # Bước 3: Thông báo
      - name: Echo Success
        run: echo "Code ngon lanh! Docker build thanh cong."